// ingredientTrie.js
// Auto-generated from ingredients-with-possible-units.xlsx
// 3439 ingredients — no API calls needed

const INGREDIENTS = [
  "1 percent chocolate milk",
  "1 percent milk",
  "2 percent milk",
  "20 percent quark",
  "40 percent quark",
  "80 percent lean ground beef",
  "85 percent lean ground beef",
  "90 percent lean ground beef",
  "93 percent lean ground turkey",
  "95 percent lean ground beef",
  "absinthe",
  "acai juice",
  "acai powder",
  "ackee",
  "acorn squash",
  "active dry yeast",
  "adobo sauce",
  "adobo seasoning",
  "adzuki beans",
  "agar",
  "agave",
  "aged balsamic vinegar",
  "agnolotti",
  "ahi tuna",
  "ahi tuna steak",
  "aioli",
  "aji amarillo",
  "aji amarillo chili paste",
  "ajwain",
  "albacore tuna packed in oil",
  "alcohol",
  "ale",
  "aleppo pepper",
  "alfalfa sprouts",
  "alfredo sauce",
  "all bran cereal",
  "all purpose flour",
  "allergy friendly chocolate chips",
  "allspice",
  "allspice berries",
  "allulose",
  "almond bark",
  "almond butter",
  "almond extract",
  "almond flour",
  "almond joy bar",
  "almond meal",
  "almond milk",
  "almond oil",
  "almond paste",
  "almonds",
  "aloe vera juice",
  "alum",
  "aluminum free baking powder",
  "amaranth",
  "amaranth flour",
  "amaretti cookie crumbs",
  "amaretti cookies",
  "amaretto liqueur",
  "amaro",
  "amchar masala",
  "amchoor",
  "american cheese",
  "amla",
  "anaheim pepper",
  "ancho chili pepper",
  "ancho chili powder",
  "anchovies",
  "anchovies in extra virgin olive oil",
  "anchovies in olive oil",
  "anchovy fillets",
  "anchovy paste",
  "andes mints",
  "andouille sausage",
  "anellini pasta",
  "angel food cake",
  "angel food cake mix",
  "angel hair pasta",
  "angostura bitters",
  "anise",
  "anise extract",
  "anisette",
  "anjou pear",
  "annatto",
  "annatto seeds",
  "any color food color",
  "aperol",
  "apple",
  "apple butter",
  "apple cider",
  "apple cider vinegar",
  "apple jelly",
  "apple juice",
  "apple pie filling",
  "apple pie spice",
  "applesauce",
  "applewood smoked bacon",
  "apricot",
  "apricot jam",
  "apricot nectar",
  "apricot pie filling",
  "apricot preserves",
  "arbol chile",
  "arborrio rice",
  "areca nut",
  "arrowroot",
  "artichoke",
  "artichoke bottoms",
  "artichoke hearts",
  "artificial vanilla",
  "arugula",
  "asafoetida",
  "ash gourd",
  "asiago cheese",
  "asian dressing",
  "asian vegetables",
  "asparagus",
  "au jus",
  "avocado",
  "avocado cubes",
  "avocado halves",
  "avocado leaves",
  "avocado oil",
  "avocado slices",
  "baby artichoke",
  "baby arugula",
  "baby back ribs",
  "baby beets",
  "baby bok choy",
  "baby carrots",
  "baby corn",
  "baby eggplant",
  "baby leaf lettuce",
  "baby leeks",
  "baby lima beans",
  "baby shrimp",
  "baby spinach",
  "baby zucchini",
  "bacon",
  "bacon bits",
  "bacon drippings",
  "bacon ends and pieces",
  "bael fruit",
  "bagel",
  "bagel chips",
  "baguette",
  "baharat",
  "baked beans",
  "baked tortilla chips",
  "bakers white chocolate",
  "baking mix",
  "baking potato",
  "baking powder",
  "baking soda",
  "balsamic glaze",
  "balsamic vinaigrette",
  "balsamic vinegar",
  "bamboo shoots",
  "banana",
  "banana blossoms",
  "banana bread",
  "banana bread mix",
  "banana chips",
  "banana extract",
  "banana leaves",
  "banana liqueur",
  "banana pepper",
  "banana pepper rings",
  "banana pudding mix",
  "banana shallot",
  "barbecue sauce",
  "barbecue seasoning",
  "barley",
  "barley flakes",
  "barley flour",
  "barnyard millet",
  "bartlett pear",
  "basil",
  "basil oil",
  "basil pesto",
  "basmati rice",
  "bay leaves",
  "bay scallops",
  "bean curd sheets",
  "bean sprouts",
  "bee pollen",
  "beef",
  "beef base",
  "beef bone",
  "beef bouillon",
  "beef bouillon cube",
  "beef bouillon granules",
  "beef bouillon powder",
  "beef brisket",
  "beef broth",
  "beef chuck roast",
  "beef consomme",
  "beef cubes",
  "beef flavored ramen",
  "beef franks",
  "beef gravy",
  "beef hearts",
  "beef jerky",
  "beef kidney",
  "beef liver",
  "beef patties",
  "beef ravioli",
  "beef round roast",
  "beef shank",
  "beef short ribs",
  "beef shoulder roast",
  "beef sirloin tip roast",
  "beef soup bone",
  "beef stew meat",
  "beef stock",
  "beef stock powder",
  "beef strip loin",
  "beef tenderloin",
  "beefsteak tomato",
  "beer",
  "beet",
  "beet greens",
  "belacan",
  "belgian endive",
  "bell pepper",
  "benedictine",
  "bengal gram",
  "berbere",
  "berries",
  "betel leaves",
  "bilimbi fruit",
  "biltong",
  "biscotti",
  "biscuit mix",
  "biscuits",
  "bison",
  "bison back ribs",
  "bison ribeye",
  "bison roast",
  "bison short ribs",
  "bison sirloin",
  "bison sirloin tip roast",
  "bison steak",
  "bison strip loin",
  "bison tenderloin",
  "bitter gourd",
  "bitters",
  "bittersweet chocolate",
  "bittersweet chocolate chips",
  "black bass",
  "black bean sauce",
  "black beans",
  "black cardamoms",
  "black cherries",
  "black currants",
  "black drum",
  "black forest ham",
  "black grapes",
  "black lentils",
  "black licorice",
  "black mustard seeds",
  "black nightshade",
  "black olives",
  "black pepper",
  "black peppercorns",
  "black plum",
  "black quinoa",
  "black rice",
  "black sesame seeds",
  "black tea",
  "black tea bag",
  "black treacle",
  "black vinegar",
  "black walnuts",
  "blackberries",
  "blackberry jam",
  "blackberry juice",
  "blackening spice",
  "blackeyed peas",
  "blanched almond flour",
  "blanched almonds",
  "blanched slivered almonds",
  "block style cream cheese",
  "blood orange",
  "blood orange juice",
  "blood orange zest",
  "blue cheese",
  "blue cheese crumbles",
  "blue cheese dressing",
  "blue food color",
  "blue spirulina",
  "blueberries",
  "blueberry bagel",
  "blueberry jam",
  "blueberry jelly",
  "blueberry juice",
  "blueberry pie filling",
  "bluefish",
  "bluefish fillets",
  "boar",
  "bocconcini",
  "boiled ham",
  "boiling potato",
  "bok choy",
  "bok choy leaves",
  "bologna",
  "bombay duck",
  "bone broth",
  "bone in beef short ribs",
  "bone in bison short ribs",
  "bone in chicken breast",
  "bone in chicken breast halves",
  "bone in chicken thighs",
  "bone in pork chops",
  "bone in pork loin",
  "bone in pork rib roast",
  "bone in pork roast",
  "bone in skin on chicken breast",
  "bone in skin on chicken breast halves",
  "bone in skin on chicken thighs",
  "bone in skin on turkey breast",
  "bone in skinless chicken thighs",
  "bone in skinless turkey breast",
  "bone in turkey breast",
  "boneless beef short ribs",
  "boneless chicken breast",
  "boneless chicken breast halves",
  "boneless chicken thighs",
  "boneless chicken wings",
  "boneless chuck steak",
  "boneless pork loin",
  "boneless pork rib roast",
  "boneless pork roast",
  "boneless pork shoulder",
  "boneless skin on chicken breast",
  "boneless skin on chicken breast halves",
  "boneless skin on chicken thighs",
  "boneless skin on turkey breast",
  "boneless skinless chicken breast",
  "boneless skinless chicken breast halves",
  "boneless skinless chicken thighs",
  "boneless skinless turkey breast",
  "boneless turkey breast",
  "bonito flakes",
  "boquerones",
  "borlotti beans",
  "bosc pear",
  "boston butt",
  "bottarga",
  "bottle gourd",
  "bottled garlic",
  "bottled ginger",
  "bouillon",
  "bouillon cube",
  "bouillon granules",
  "bouillon powder",
  "boule",
  "bouquet garni",
  "bourbon",
  "bourbon vanilla extract",
  "boursin cheese",
  "boysenberries",
  "braeburn apple",
  "braggs liquid aminos",
  "bramley apple",
  "bran",
  "bran flakes",
  "brandy",
  "bratwurst",
  "bratwurst bun",
  "brazil nuts",
  "bread",
  "bread bowls",
  "bread cubes",
  "bread dough",
  "bread flour",
  "bread machine yeast",
  "breadcrumbs",
  "breadfruit",
  "breadstick dough",
  "breakfast sausage",
  "brewed coffee",
  "brewers yeast",
  "brie",
  "brine",
  "brioche",
  "brioche bun",
  "broccoli",
  "broccoli carrot cauliflower mix",
  "broccoli coleslaw mix",
  "broccoli florets",
  "broccoli rabe",
  "broccoli slaw",
  "broccoli sprouts",
  "broccolini",
  "broth",
  "brown gravy",
  "brown lentils",
  "brown mustard seeds",
  "brown rice",
  "brown rice flour",
  "brown rice pasta",
  "brown rice syrup",
  "brown sugar",
  "brownie mix",
  "browning sauce",
  "brussels sprouts",
  "brut cava",
  "brut prosecco",
  "bucatini",
  "buckwheat",
  "buckwheat flour",
  "buffalo mozzarella",
  "buffalo sauce",
  "bulgur",
  "burdock root",
  "burrata",
  "burrito size tortilla",
  "butter",
  "butter beans",
  "butter crackers",
  "butter flavored cooking spray",
  "butter flavored shortening",
  "butter lettuce",
  "butter lettuce leaves",
  "buttercup squash",
  "butterfinger candy bar",
  "butterflied trout",
  "buttermilk",
  "buttermilk biscuits",
  "buttermilk powder",
  "butternut squash",
  "butterscotch",
  "butterscotch chips",
  "butterscotch pudding",
  "butterscotch pudding mix",
  "buttery round crackers",
  "cabbage",
  "cabernet sauvignon",
  "cacao powder",
  "cachaca",
  "caerphilly",
  "caesar salad dressing",
  "cajun seasoning",
  "cajun stewed tomatoes",
  "cake flour",
  "cake mix",
  "calumet baking powder",
  "calvados",
  "camembert",
  "campari",
  "canadian bacon",
  "candied almonds",
  "candied cherries",
  "candied citron",
  "candied fruit",
  "candied ginger",
  "candied nuts",
  "candied orange peel",
  "candied pecans",
  "candied walnuts",
  "candlenuts",
  "candy cane",
  "candy coated chocolate pieces",
  "candy corn",
  "candy melts",
  "canned adzuki beans",
  "canned albacore tuna",
  "canned anchovies",
  "canned asparagus",
  "canned baby limas beans",
  "canned beans",
  "canned beef broth",
  "canned beets",
  "canned black beans",
  "canned blackeyed peas",
  "canned borlotti beans",
  "canned boysenberries",
  "canned butter beans",
  "canned cannellini beans",
  "canned chicken",
  "canned chicken breast",
  "canned chickpeas",
  "canned chipotle chile",
  "canned chipotle chiles in adobo",
  "canned coconut milk",
  "canned corn",
  "canned corona beans",
  "canned cranberry beans",
  "canned diced tomatoes",
  "canned fava beans",
  "canned fish",
  "canned gigante beans",
  "canned great northern beans",
  "canned green chiles",
  "canned herring",
  "canned jackfruit",
  "canned kidney beans",
  "canned lentils",
  "canned lima beans",
  "canned lychees",
  "canned mackerel",
  "canned mandarin oranges",
  "canned mushrooms",
  "canned navy beans",
  "canned peas",
  "canned peas and carrots",
  "canned pigeon peas",
  "canned pineapple",
  "canned pinto beans",
  "canned pumpkin",
  "canned red kidney beans",
  "canned salmon",
  "canned sardines",
  "canned smoked salmon",
  "canned soybeans",
  "canned sprats",
  "canned tomato sauce",
  "canned tomatoes",
  "canned tuna",
  "canned water chestnuts",
  "canned white beans",
  "canned white kidney beans",
  "canned whole tomatoes",
  "canned zucchini",
  "cannellini beans",
  "cannoli shells",
  "canola oil",
  "cantaloupe",
  "cantaloupe balls",
  "capellini",
  "caper berries",
  "capers",
  "capicola",
  "captain crunch",
  "caramel",
  "caramel candy",
  "caramel popcorn",
  "caramel sauce",
  "caramelized onions",
  "caraway seeds",
  "carbiquick",
  "cardamom",
  "cardamom pods",
  "cardamom powder",
  "carob chips",
  "carob powder",
  "carp",
  "carrot",
  "carrot juice",
  "carrot leaves",
  "carrot quickbread mix",
  "cashew butter",
  "cashew fruit",
  "cashew halves",
  "cashew milk",
  "cashews",
  "cassava",
  "cassava flour",
  "catalina dressing",
  "catfish",
  "catfish fillets",
  "cauliflower",
  "cauliflower florets",
  "cauliflower rice",
  "cava",
  "cavatappi",
  "cavatelli",
  "caviar",
  "caviar substitute",
  "cayenne pepper",
  "cedar plank",
  "celeriac",
  "celery",
  "celery flakes",
  "celery leaves",
  "celery rib",
  "celery salt",
  "celery seed",
  "cellophane noodles",
  "cereal",
  "chaat masala",
  "chablis",
  "chai",
  "chai spice",
  "chai tea bag",
  "challah",
  "challah roll",
  "chambord",
  "champagne",
  "champagne vinegar",
  "chana dal",
  "chanterelle mushrooms",
  "chardonnay",
  "charoli seeds",
  "chartreuse",
  "chayote",
  "cheddar cheese",
  "cheddar cheese soup",
  "cheerios",
  "cheese",
  "cheese curds",
  "cheese dip",
  "cheese pumpkin",
  "cheese ravioli",
  "cheese tortellini",
  "cheesecake mix",
  "cheez whiz",
  "cherries",
  "cherry flavored gelatin",
  "cherry jam",
  "cherry juice",
  "cherry pie filling",
  "cherry preserves",
  "cherry tomato",
  "chervil",
  "cheshire cheese",
  "chestnut flour",
  "chestnut mushrooms",
  "chestnuts",
  "chex cereal",
  "chex mix",
  "chia egg",
  "chia seeds",
  "chianti",
  "chicken",
  "chicken base",
  "chicken bones",
  "chicken bouillon",
  "chicken bouillon cube",
  "chicken bouillon granules",
  "chicken bouillon powder",
  "chicken bratwurst",
  "chicken breast",
  "chicken breast halves",
  "chicken breast meat",
  "chicken broth",
  "chicken cutlet",
  "chicken drumettes",
  "chicken drumsticks",
  "chicken fat",
  "chicken feet",
  "chicken giblets",
  "chicken gravy",
  "chicken hearts",
  "chicken leg",
  "chicken leg quarters",
  "chicken liver",
  "chicken pieces",
  "chicken sausage",
  "chicken schmaltz",
  "chicken seasoning",
  "chicken stock",
  "chicken stock powder",
  "chicken tenderloins",
  "chicken tenders",
  "chicken thigh fillets",
  "chicken thighs",
  "chicken wings",
  "chickpea elbow macaroni",
  "chickpea flour",
  "chickpea leaves",
  "chickpea pasta",
  "chickpea penne",
  "chickpea rotini",
  "chickpea spaghetti",
  "chickpeas",
  "chilean seabass",
  "chili beans",
  "chili garlic sauce",
  "chili oil",
  "chili paste",
  "chili pepper",
  "chili powder",
  "chili sauce",
  "chili seasoning mix",
  "chili with beans",
  "chili without beans",
  "chinese cabbage",
  "chinese egg noodles",
  "chinese five spice",
  "chinese rice wine",
  "chipolata",
  "chipotle chile puree",
  "chipotle chiles",
  "chipotle paste",
  "chipotle pepper flakes",
  "chive and onion cream cheese spread",
  "chives",
  "chocolate",
  "chocolate cake mix",
  "chocolate chip cookies",
  "chocolate chips",
  "chocolate chunks",
  "chocolate cookies",
  "chocolate covered caramel candy",
  "chocolate covered coffee beans",
  "chocolate covered espresso beans",
  "chocolate covered raisins",
  "chocolate covered sunflower seeds",
  "chocolate crumb crust",
  "chocolate cupcake mix",
  "chocolate curls",
  "chocolate digestive biscuits",
  "chocolate eggs",
  "chocolate extract",
  "chocolate flakes",
  "chocolate frosting",
  "chocolate glaze",
  "chocolate graham cracker crumbs",
  "chocolate hazelnut spread",
  "chocolate ice cream",
  "chocolate malt powder",
  "chocolate milk",
  "chocolate milk powder",
  "chocolate mint",
  "chocolate protein powder",
  "chocolate sandwich cookies",
  "chocolate shavings",
  "chocolate soy pudding",
  "chocolate sprinkles",
  "chocolate syrup",
  "chocolate wafer cookies",
  "chocolate wafer crumbs",
  "chokeberries",
  "chopped dried pears",
  "chorizo",
  "chorizo crumbles",
  "chorizo sausages",
  "chow mein noodles",
  "choy sum",
  "chuck steak",
  "ciabatta",
  "ciabatta roll",
  "ciabatta sandwich roll",
  "cilantro",
  "cinnamon",
  "cinnamon bagels",
  "cinnamon roll",
  "cinnamon schnapps",
  "cinnamon stick",
  "cinnamon sugar",
  "cinnamon sugar butter",
  "cipollini onions",
  "citric acid",
  "citron",
  "clabber girl baking powder",
  "clam juice",
  "clams",
  "clarified butter",
  "clear glaze",
  "clear honey",
  "clementine",
  "clementine juice",
  "clotted cream",
  "clove",
  "cluster bean",
  "coarse grain mustard",
  "coarse kosher salt",
  "coarse salt",
  "coarse sea salt",
  "coarse sugar",
  "coca cola",
  "cockles",
  "cocktail sausages",
  "cocktail turkey sausages",
  "cocoa krispies cereal",
  "cocoa nibs",
  "cocoa pebbles cereal",
  "cocoa powder",
  "cocoa puffs cereal",
  "coconut",
  "coconut aminos",
  "coconut butter",
  "coconut cream",
  "coconut creamer",
  "coconut extract",
  "coconut flakes",
  "coconut flour",
  "coconut meat",
  "coconut milk",
  "coconut milk beverage",
  "coconut milk powder",
  "coconut oil",
  "coconut pecan frosting",
  "coconut rum",
  "coconut sugar",
  "coconut vinegar",
  "coconut water",
  "coconut wrap",
  "cod",
  "cod fillets",
  "coffee",
  "coffee beans",
  "coffee extract",
  "coffee liqueur",
  "cognac",
  "cointreau",
  "cola",
  "colby cheese",
  "colby jack",
  "coleslaw dressing",
  "coleslaw mix",
  "collagen powder",
  "collard greens",
  "colored nonpareils",
  "colored sprinkles",
  "comte",
  "concentrated crushed tomatoes",
  "concord grapes",
  "condensed cream of celery soup",
  "condensed cream of chicken soup",
  "condensed cream of mushroom soup",
  "condensed french onion soup",
  "condensed tomato soup",
  "conversation hearts",
  "cooked amaranth",
  "cooked anellini pasta",
  "cooked angel hair pasta",
  "cooked arborrio rice",
  "cooked bacon",
  "cooked basmati rice",
  "cooked beef patties",
  "cooked black lentils",
  "cooked black rice",
  "cooked brown lentils",
  "cooked brown rice",
  "cooked bucatini",
  "cooked buckwheat",
  "cooked bulgur",
  "cooked cannelloni",
  "cooked capellini",
  "cooked cavatappi",
  "cooked cellophane noodles",
  "cooked cheese tortellini",
  "cooked chicken",
  "cooked chicken breast",
  "cooked chow mein noodles",
  "cooked corkscrew pasta",
  "cooked couscous",
  "cooked crabmeat",
  "cooked ditalini",
  "cooked egg noodles",
  "cooked elbow macaroni",
  "cooked farfalle",
  "cooked farfalle tonde",
  "cooked farro",
  "cooked fettuccine",
  "cooked fusilli",
  "cooked gemelli",
  "cooked gluten free farfalle",
  "cooked gluten free fusili",
  "cooked gluten free pasta",
  "cooked gluten free spaghetti",
  "cooked glutinous rice",
  "cooked grain blend",
  "cooked green lentils",
  "cooked grits",
  "cooked ham",
  "cooked hash browns",
  "cooked instant brown rice",
  "cooked instant grits",
  "cooked instant white rice",
  "cooked israeli couscous",
  "cooked jasmine rice",
  "cooked jumbo pasta shells",
  "cooked kamut",
  "cooked lasagne noodles",
  "cooked lentils",
  "cooked linguine",
  "cooked long grain brown rice",
  "cooked long grain rice",
  "cooked long grain white rice",
  "cooked long pasta",
  "cooked macaroni",
  "cooked manicotti",
  "cooked medium grain rice",
  "cooked mostaccioli",
  "cooked mung beans",
  "cooked orecchiette",
  "cooked orzo",
  "cooked pappardelle",
  "cooked pasta",
  "cooked pasta shells",
  "cooked pastina",
  "cooked pearl barley",
  "cooked penne",
  "cooked pork",
  "cooked quick cooking grits",
  "cooked quick cooking oats",
  "cooked quinoa",
  "cooked ramen noodles",
  "cooked red lentils",
  "cooked rice",
  "cooked rice noodles",
  "cooked rice vermicelli",
  "cooked rigatoni",
  "cooked risotto rice",
  "cooked rolled oats",
  "cooked rotini",
  "cooked short grain brown rice",
  "cooked short grain rice",
  "cooked short pasta",
  "cooked soba noodles",
  "cooked spaghetti",
  "cooked spaghettini",
  "cooked spelt",
  "cooked spinach tortellini",
  "cooked split peas",
  "cooked steel cut oats",
  "cooked sticky rice",
  "cooked sushi rice",
  "cooked tagliatelle",
  "cooked tortellini",
  "cooked udon noodles",
  "cooked wheatberries",
  "cooked white rice",
  "cooked whole wheat angel hair pasta",
  "cooked whole wheat farfalle",
  "cooked whole wheat pasta",
  "cooked whole wheat pasta shells",
  "cooked whole wheat spaghetti",
  "cooked wide egg noodles",
  "cooked wild rice",
  "cooked yellow split peas",
  "cooked ziti",
  "cookie butter",
  "cookie crumbs",
  "cookie mix",
  "cookies",
  "cooking oil",
  "cooking spray",
  "coriander",
  "corkscrew pasta",
  "corn",
  "corn cereal",
  "corn chex",
  "corn chips",
  "corn flake crumbs",
  "corn flakes",
  "corn flour",
  "corn husks",
  "corn kernels",
  "corn muffin mix",
  "corn oil",
  "corn on the cob",
  "corn starch",
  "corn syrup",
  "corn tortilla",
  "corn tortilla chips",
  "cornbread",
  "cornbread mix",
  "corned beef",
  "corned beef brisket",
  "cornish hens",
  "cornmeal",
  "cornmeal mix",
  "corona beans",
  "cotija cheese",
  "cottage cheese",
  "country ham",
  "country style beef ribs",
  "country style pork ribs",
  "country style ribs",
  "couscous",
  "couverture",
  "cowpea green beans",
  "crab",
  "crab boil seasoning",
  "crabmeat",
  "cracked wheat",
  "cracker crumbs",
  "crackers",
  "craisins",
  "cranberries",
  "cranberry beans",
  "cranberry juice",
  "cranberry juice cocktail",
  "cranberry juice concentrate",
  "crawfish",
  "crawfish tails",
  "cream",
  "cream cheese",
  "cream cheese frosting",
  "cream of celery soup",
  "cream of chicken soup",
  "cream of coconut",
  "cream of mushroom soup",
  "cream of potato soup",
  "cream of tartar",
  "cream of wheat",
  "cream sherry",
  "cream soda",
  "creamed coconut",
  "creamed corn",
  "creamy peanut butter",
  "creme de cacao",
  "creme de menthe",
  "creme de menthe baking pieces",
  "creme fraiche",
  "creole mustard",
  "creole seasoning",
  "crepes",
  "crescent roll dough",
  "cress seed",
  "crimini mushrooms",
  "crisco",
  "crispbread",
  "crispy chow mein noodles",
  "crocodile meat",
  "croissant",
  "crostini",
  "croutons",
  "crunchy peanut butter",
  "crushed ice cubes",
  "crushed pineapple",
  "crushed shortbread cookies",
  "crushed tomatoes",
  "crusty bread",
  "crusty roll",
  "cubanelle pepper",
  "cube steak",
  "cucumber",
  "culantro",
  "cumin",
  "cumin seeds",
  "cupcakes",
  "curacao",
  "curly endive",
  "curly leaf lettuce",
  "curly leaf lettuce leaves",
  "curly parsley",
  "currants",
  "curry leaves",
  "curry paste",
  "curry powder",
  "cushaw squash",
  "custard",
  "custard apple",
  "custard powder",
  "cuttlefish",
  "daikon radish",
  "daikon sprouts",
  "dandelion greens",
  "dark beer",
  "dark brown sugar",
  "dark chocolate",
  "dark chocolate bar",
  "dark chocolate chips",
  "dark chocolate couverture",
  "dark corn syrup",
  "dark molasses",
  "dark muscovado sugar",
  "dark rum",
  "dark sesame oil",
  "dashi",
  "dates",
  "decaf coffee",
  "decorating gel",
  "deep dish pie crust",
  "defatted peanut flour",
  "defatted soy flour",
  "dehydrated garlic",
  "deli turkey",
  "delicata squash",
  "demerara sugar",
  "demi glace",
  "desiccated coconut",
  "dessert shells",
  "dessert wine",
  "devils food cake mix",
  "diced green chiles",
  "diced ham",
  "diced tomatoes with green chilies",
  "diced venison",
  "diet coke",
  "diet cola",
  "diet pop",
  "diet root beer",
  "digestive biscuits",
  "dijon mustard",
  "dill",
  "dill pickle slices",
  "dill pickles",
  "dill seed",
  "distilled white vinegar",
  "ditalini",
  "double cream",
  "double gloucester",
  "douchi",
  "dr pepper",
  "dragon fruit",
  "drambuie",
  "dried adzuki beans",
  "dried apples",
  "dried apricots",
  "dried arbol chile",
  "dried baby lima beans",
  "dried barberries",
  "dried basil",
  "dried bay leaves",
  "dried beans",
  "dried black beans",
  "dried black lentils",
  "dried blackeyed peas",
  "dried blueberries",
  "dried borlotti beans",
  "dried brown lentils",
  "dried butter beans",
  "dried cannellini beans",
  "dried cheese tortellini",
  "dried cherries",
  "dried chickpeas",
  "dried chili pepper",
  "dried chipotles",
  "dried chives",
  "dried cilantro",
  "dried coconut",
  "dried corona beans",
  "dried cranberries",
  "dried cranberry beans",
  "dried currants",
  "dried dill",
  "dried egg whites",
  "dried epazote",
  "dried fava beans",
  "dried fenugreek leaves",
  "dried figs",
  "dried fruit",
  "dried gigante beans",
  "dried great northern beans",
  "dried green lentils",
  "dried green peas",
  "dried herbs",
  "dried hibiscus",
  "dried kidney beans",
  "dried lentils",
  "dried lima beans",
  "dried mango",
  "dried marjoram",
  "dried mint",
  "dried mung beans",
  "dried navy beans",
  "dried onion",
  "dried onion flakes",
  "dried parsley",
  "dried peaches",
  "dried pears",
  "dried pigeon peas",
  "dried pineapple",
  "dried pinto beans",
  "dried porcini mushrooms",
  "dried red kidney beans",
  "dried red lentils",
  "dried rosemary",
  "dried sage",
  "dried shiitake mushrooms",
  "dried shrimp",
  "dried soybeans",
  "dried spinach tortellini",
  "dried strawberries",
  "dried sweetened cranberries",
  "dried tarragon",
  "dried thyme",
  "dried tortellini",
  "dried white beans",
  "dried white kidney beans",
  "dry cider",
  "dry couscous",
  "dry israeli couscous",
  "dry onion soup mix",
  "dry ranch dressing mix",
  "dry red wine",
  "dry riesling",
  "dry roasted peanuts",
  "dry roasted salted sunflower seeds",
  "dry seasoning rub",
  "dry sherry",
  "dry vermouth",
  "dry white wine",
  "dry yeast",
  "duck",
  "duck breast",
  "duck eggs",
  "duck fat",
  "duck leg",
  "duck liver",
  "dulce de leche",
  "dulse",
  "dumpling wrappers",
  "dungeness crab",
  "durian",
  "durum flour",
  "dutch processed cocoa powder",
  "earl grey",
  "edam cheese",
  "edamame",
  "edamame in the pod",
  "edible flowers",
  "edible gold",
  "eel",
  "egg",
  "egg noodles",
  "egg replacer",
  "egg roll wrappers",
  "egg substitute",
  "egg whites",
  "egg yolk",
  "eggbeaters",
  "eggnog",
  "eggplant",
  "elbow macaroni",
  "elderberries",
  "elderflower",
  "elderflower liqueur",
  "elk",
  "elk roast",
  "elk sausage",
  "elk steak",
  "elk tenderloin",
  "emmantaler cheese",
  "empanada dough",
  "enchilada sauce",
  "enchilado cheese",
  "endive",
  "ener g egg replacer",
  "english cucumber",
  "english muffin",
  "english mustard",
  "enoki mushrooms",
  "entrecote steak",
  "epazote",
  "erythritol",
  "escargot",
  "escarole",
  "espresso",
  "european seabass",
  "evaporated cane juice",
  "evaporated milk",
  "evaporated skim milk",
  "everything bagel",
  "everything bagel seasoning",
  "expeller pressed canola oil",
  "extra dry prosecco",
  "extra firm tofu",
  "extra sharp cheddar cheese",
  "extra virgin olive oil",
  "ez sweetz",
  "falernum syrup",
  "falsa",
  "farfalle",
  "farfalle tonde",
  "farm raised catfish fillets",
  "farmer cheese",
  "farro",
  "fat free buttermilk",
  "fat free cheddar cheese",
  "fat free chicken broth",
  "fat free cottage cheese",
  "fat free cream cheese",
  "fat free feta cheese",
  "fat free greek yogurt",
  "fat free half and half",
  "fat free less sodium beef broth",
  "fat free mayonnaise",
  "fat free milk",
  "fat free parmesan cheese",
  "fat free ricotta cheese",
  "fat free vanilla greek yogurt",
  "fat free vanilla yogurt",
  "fat free whipped topping",
  "fat free yogurt",
  "fat of choice",
  "fatback",
  "fava beans",
  "feijoa",
  "fennel",
  "fennel bulb",
  "fennel pollen",
  "fennel seeds",
  "fenugreek seeds",
  "fernet branca",
  "feta cheese",
  "fettuccine",
  "fiddleheads",
  "fig jam",
  "figs",
  "file powder",
  "filet mignon",
  "filo pastry",
  "fine cornmeal",
  "fine salt",
  "fine sea salt",
  "finely crushed pretzels",
  "finely grated lime zest",
  "finger chili",
  "finger millet",
  "fingerling potato",
  "fiori di sicilia",
  "fire roasted tomatoes",
  "firm tofu",
  "fish",
  "fish fillets",
  "fish sauce",
  "fish seasoning",
  "fish stock",
  "flacourtia",
  "flank steak",
  "flat iron steak",
  "flat leaf parsley",
  "flatbread",
  "flavored butter",
  "flavored sugar",
  "flavoring syrup",
  "flax egg",
  "flax oil",
  "flaxseed",
  "fleur de sel",
  "flounder",
  "flounder fillets",
  "flour tortilla",
  "focaccia",
  "foie gras",
  "fontina cheese",
  "food color",
  "framboise lambic",
  "framboise liqueur",
  "frangelico",
  "freekeh",
  "freeze dried strawberries",
  "fregula",
  "french bread",
  "french dressing",
  "french fries",
  "french lentils",
  "french mustard",
  "fresh anchovies",
  "fresh basil",
  "fresh bay leaves",
  "fresh cayenne pepper",
  "fresh chives",
  "fresh cilantro",
  "fresh corn",
  "fresh corn kernels",
  "fresh dill",
  "fresh epazote",
  "fresh fenugreek leaves",
  "fresh figs",
  "fresh flat leaf parsley",
  "fresh fruit",
  "fresh ginger",
  "fresh green beans",
  "fresh herbs",
  "fresh herring",
  "fresh lasagne sheets",
  "fresh lavender",
  "fresh marjoram",
  "fresh mint",
  "fresh mozzarella",
  "fresh mushrooms",
  "fresh nutmeg",
  "fresh oregano",
  "fresh parsley",
  "fresh pasta",
  "fresh peas",
  "fresh rosemary",
  "fresh sage",
  "fresh sardines",
  "fresh tarragon",
  "fresh thyme",
  "fresh tuna",
  "fresh yeast",
  "fresine",
  "fresno pepper",
  "fried onions",
  "frog legs",
  "froot loops cereal",
  "frosted flakes",
  "frosting",
  "frozen artichoke hearts",
  "frozen baby lima beans",
  "frozen biscuits",
  "frozen cheesecake",
  "frozen corn",
  "frozen low fat waffles",
  "frozen pizza",
  "frozen spinach",
  "frozen waffles",
  "frozen yogurt",
  "fruit",
  "fruit cocktail",
  "fruit juice",
  "fruit pectin",
  "fruit slices",
  "fruity pebbles cereal",
  "fudge",
  "fudge ice cream topping",
  "fuji apple",
  "full bodied red wine",
  "funfetti cake mix",
  "fusilli",
  "fuyu persimmon",
  "gala apple",
  "galangal",
  "galliano",
  "gammon",
  "gammon steak",
  "garam masala",
  "garden cress",
  "garlic",
  "garlic herb spreadable cheese",
  "garlic oil",
  "garlic paste",
  "garlic powder",
  "garlic salt",
  "garlic scapes",
  "gelatin",
  "gelling sugar",
  "gem squash",
  "gemelli",
  "genever",
  "german sweet chocolate",
  "ghee",
  "gherkins",
  "gigante beans",
  "gin",
  "ginger",
  "ginger ale",
  "ginger beer",
  "ginger garlic paste",
  "ginger juice",
  "ginger paste",
  "ginger powder",
  "gingerbread spice",
  "gingersnap cookies",
  "gingersnap crumbs",
  "ginseng root",
  "globe eggplant",
  "glucose syrup",
  "gluten free all purpose flour",
  "gluten free angel food cake mix",
  "gluten free bagel",
  "gluten free baking mix",
  "gluten free bread",
  "gluten free bread flour",
  "gluten free breadcrumbs",
  "gluten free brownie mix",
  "gluten free cheerios",
  "gluten free chocolate cake mix",
  "gluten free chocolate cookies",
  "gluten free chocolate sandwich cookies",
  "gluten free corn flakes",
  "gluten free cornbread mix",
  "gluten free crackers",
  "gluten free croissant",
  "gluten free elbow macaroni",
  "gluten free farfalle",
  "gluten free flour",
  "gluten free flour mix",
  "gluten free french bread",
  "gluten free frozen pie crust",
  "gluten free funfetti cake mix",
  "gluten free fusili",
  "gluten free gingersnap cookies",
  "gluten free graham cracker squares",
  "gluten free graham crackers",
  "gluten free granola",
  "gluten free hamburger bun",
  "gluten free hot dog bun",
  "gluten free ladyfingers",
  "gluten free lasagne noodles",
  "gluten free macaroni",
  "gluten free muffin mix",
  "gluten free pancake mix",
  "gluten free panko",
  "gluten free pasta",
  "gluten free pie crust",
  "gluten free pie dough",
  "gluten free pizza dough",
  "gluten free pizza dough mix",
  "gluten free pretzels",
  "gluten free refrigerated pie crusts",
  "gluten free shortbread cookies",
  "gluten free spaghetti",
  "gluten free stuffing mix",
  "gluten free sugar cookie mix",
  "gluten free tortilla",
  "gluten free vanilla cake mix",
  "gluten free vanilla sandwich cookies",
  "gluten free white cake mix",
  "gluten free white sandwich bread",
  "gluten free wrap",
  "gluten free yellow cake mix",
  "glutinous rice",
  "gnocchi",
  "goat cheese",
  "goat milk",
  "gochugaru",
  "gochujang",
  "goji berries",
  "golden beet",
  "golden berries",
  "golden brown sugar",
  "golden cherries",
  "golden delicious apple",
  "golden kiwi",
  "golden oreos",
  "golden raisins",
  "golden syrup",
  "goldfish crackers",
  "gomashio",
  "goose",
  "goose fat",
  "goose liver",
  "gooseberries",
  "gorgonzola",
  "gouda",
  "graham cracker crumbs",
  "graham cracker pie crust",
  "graham cracker squares",
  "graham crackers",
  "graham flour",
  "grain blend",
  "grana padano",
  "grand marnier",
  "granny smith apple",
  "granola",
  "granulated garlic",
  "granulated lemon sugar",
  "granulated onion",
  "granulated sugar",
  "grape jam",
  "grape jelly",
  "grape juice",
  "grape leaves",
  "grape nuts cereal",
  "grape seed flour",
  "grape seed oil",
  "grape tomato",
  "grapefruit",
  "grapefruit juice",
  "grapefruit zest",
  "grapes",
  "grappa",
  "grated parmesan cheese",
  "gravlax",
  "gravy",
  "great northern beans",
  "greek olives",
  "greek seasoning",
  "greek yogurt",
  "green apple",
  "green beans",
  "green cabbage",
  "green cardamoms",
  "green chili pepper",
  "green curry paste",
  "green enchilada sauce",
  "green food color",
  "green grapes",
  "green hot sauce",
  "green mango",
  "green olives",
  "green onions",
  "green papaya",
  "green peas",
  "green pepper",
  "green peppercorns",
  "green pesto",
  "green plantain",
  "green prawns",
  "green tea",
  "green tea bag",
  "green tomato",
  "greens",
  "grenadine",
  "grill seasoning",
  "grilled chicken",
  "grilling cheese",
  "grissini",
  "grits",
  "ground all white meat turkey",
  "ground allspice",
  "ground beef",
  "ground bison",
  "ground black pepper",
  "ground cayenne pepper",
  "ground chicken",
  "ground chipotle chile pepper",
  "ground chorizo",
  "ground chuck",
  "ground cinnamon",
  "ground clove",
  "ground coffee",
  "ground coriander",
  "ground cumin",
  "ground elk",
  "ground espresso",
  "ground fennel",
  "ground fenugreek",
  "ground flaxseed",
  "ground lamb",
  "ground mace",
  "ground pork",
  "ground pork sausage",
  "ground round",
  "ground sage",
  "ground savory",
  "ground sirloin",
  "ground thyme",
  "ground turkey",
  "ground veal",
  "ground venison",
  "ground white pepper",
  "grouper",
  "grouper fillets",
  "grouse",
  "gruyere",
  "guacamole",
  "guajillo pepper",
  "guanciale",
  "guar gum",
  "guava",
  "guava juice",
  "guava nectar",
  "guava shells",
  "guinea fowl",
  "guinness",
  "gum drops",
  "gummy worms",
  "habanero chili",
  "haddock",
  "haddock fillets",
  "hake",
  "half and half",
  "halibut",
  "halibut fillets",
  "halibut steaks",
  "halloumi",
  "halloween sprinkles",
  "ham",
  "ham bone",
  "ham hock",
  "ham slices",
  "ham steak",
  "hamburger bun",
  "hamburger helper",
  "hard boiled egg",
  "hare",
  "haricots verts",
  "harissa",
  "hash browns",
  "hass avocado",
  "havarti",
  "hawaiian bread",
  "hawaiian rock cod",
  "hawaiian roll",
  "hazelnut flour",
  "hazelnut liqueur",
  "hazelnut meal",
  "hazelnut milk",
  "hazelnut oil",
  "hazelnuts",
  "hearts of palm",
  "heath bar",
  "heavy cream",
  "heirloom tomato",
  "hemp milk",
  "hemp oil",
  "hemp protein powder",
  "hemp seeds",
  "herbes de provence",
  "herbs",
  "herring",
  "herring fillets",
  "hersheys cocoa",
  "hersheys kisses",
  "hersheys kisses brand milk chocolates",
  "hibiscus",
  "high gluten flour",
  "hoisin sauce",
  "hokkien noodles",
  "hollandaise sauce",
  "hollandaise sauce mix",
  "homemade granola",
  "hominy",
  "honey",
  "honey dijon mustard",
  "honey mustard",
  "honeydew melon",
  "horseradish",
  "horseradish root",
  "horseradish sauce",
  "hot cherry pepper",
  "hot chocolate",
  "hot cocoa mix",
  "hot dog bun",
  "hot dogs",
  "hot fudge sauce",
  "hot giardiniera",
  "hot sauce",
  "hp sauce",
  "hubbard squash",
  "huckleberries",
  "hummus",
  "hungarian paprika",
  "hungarian sweet paprika",
  "ice",
  "ice cream",
  "ice cream cone",
  "ice cream sandwiches",
  "ice cubes",
  "iceberg lettuce",
  "iceburg lettuce leaves",
  "iced tea",
  "icing",
  "imitation crab",
  "imitation lobster",
  "in shell walnuts",
  "instant brown rice",
  "instant cheesecake pudding mix",
  "instant chocolate pudding mix",
  "instant coffee",
  "instant espresso",
  "instant grits",
  "instant lemon pudding mix",
  "instant oatmeal",
  "instant pistachio pudding mix",
  "instant potatoes flakes",
  "instant vanilla pudding mix",
  "instant white rice",
  "instant yeast",
  "ipa",
  "irish cream",
  "irish moss",
  "israeli couscous",
  "italian bread",
  "italian cheese",
  "italian dressing",
  "italian salad dressing mix",
  "italian sausage",
  "italian seasoned breadcrumbs",
  "italian seasoning",
  "italian toast crackers",
  "italian tomato",
  "italian turkey sausage",
  "jackfruit",
  "jaegermeister",
  "jaggery",
  "jalapeno jelly",
  "jalapeno pepper",
  "jam",
  "jamon",
  "jamon iberico",
  "jamon serrano",
  "japanese eggplant",
  "japanese persimmon",
  "jarlsberg cheese",
  "jarrahdale squash",
  "jarred sour cherries",
  "jasmine rice",
  "jelly",
  "jelly beans",
  "jerk seasoning",
  "jerusalem artichoke",
  "jicama",
  "jobs tears",
  "juice",
  "jujubes",
  "jumbo marshmallows",
  "jumbo pasta shells",
  "jumbo shrimp",
  "juniper berries",
  "kabocha squash",
  "kaffir lime leaves",
  "kahlua",
  "kalamata olives",
  "kale",
  "kamut",
  "katsu sauce",
  "katuk",
  "kecap manis",
  "kefir",
  "kelp",
  "kelp flakes",
  "kelp noodles",
  "ketchup",
  "khesari dal",
  "khoa",
  "kidney",
  "kidney beans",
  "kielbasa",
  "kimchi",
  "king trumpet mushrooms",
  "kirsch",
  "kit kat",
  "kiwi",
  "knackwurst",
  "kohlrabi",
  "kombu",
  "korean bbq marinade",
  "kosher dill sandwich slices",
  "kosher salt",
  "kraft singles",
  "kumquat",
  "lacinato kale",
  "ladyfingers",
  "lager",
  "lamb",
  "lamb bones",
  "lamb chop",
  "lamb cutlets",
  "lamb liver",
  "lamb loin",
  "lamb loin chop",
  "lamb rib chops",
  "lamb shanks",
  "lamb shoulder",
  "lamb stew meat",
  "lamb stock",
  "lamb stock powder",
  "lambsquarters",
  "lancashire",
  "langostino tails",
  "langoustines",
  "langsat",
  "lasagne noodles",
  "lavash bread",
  "lavender honey",
  "lavender syrup",
  "lean bacon",
  "lean bone in pork chop",
  "lean chuck steak",
  "lean corned beef",
  "lean filet mignon",
  "lean ground beef",
  "lean ground lamb",
  "lean lamb loin chop",
  "lean pork loin chops",
  "lean pork tenderloin",
  "lean rack of lamb",
  "lean strip steak",
  "lebanese cucumber",
  "leek",
  "leftover turkey",
  "leg of lamb",
  "leg of wild boar",
  "legumes",
  "lemon",
  "lemon balm",
  "lemon basil",
  "lemon cake mix",
  "lemon curd",
  "lemon essence",
  "lemon extract",
  "lemon flavored gelatin",
  "lemon grass",
  "lemon jello",
  "lemon juice",
  "lemon lime pop",
  "lemon oil",
  "lemon peel",
  "lemon pepper",
  "lemon pie filling",
  "lemon sole",
  "lemon sorbet",
  "lemon sugar",
  "lemon thyme",
  "lemon wedge",
  "lemon zest",
  "lemonade",
  "lemonade concentrate",
  "lemonade mix",
  "lentils",
  "lettuce",
  "lettuce leaf",
  "licor 43",
  "licorice extract",
  "licorice twists",
  "light asian dressing",
  "light beer",
  "light brown sugar",
  "light buttery spread",
  "light chocolate ice cream",
  "light coconut milk",
  "light cream",
  "light ice cream",
  "light mayonnaise",
  "light muscovado sugar",
  "light olive oil",
  "light rum",
  "light salad dressing",
  "light sour cream",
  "light soy sauce",
  "light tuna",
  "light vanilla ice cream",
  "lightly sweetened whipped cream",
  "lillet blanc",
  "lima beans",
  "lime",
  "lime curd",
  "lime flavored gelatin",
  "lime jello",
  "lime juice",
  "lime leaves",
  "lime peel",
  "lime slice",
  "lime wedge",
  "lime zest",
  "limeade",
  "limeade concentrate",
  "limoncello",
  "limonia",
  "lingonberries",
  "lingonberry jam",
  "linguine",
  "lions mane mushrooms",
  "liquid egg whites",
  "liquid honey",
  "liquid pectin",
  "liquid smoke",
  "liquid stevia",
  "liquid sucralose",
  "liquor",
  "littleneck clams",
  "liver",
  "liver cheese",
  "liverwurst",
  "lo mein noodles",
  "lobster",
  "lobster meat",
  "lobster mushrooms",
  "lobster tails",
  "lollo rosso",
  "long grain brown rice",
  "long grain rice",
  "long grain white rice",
  "long hot pepper",
  "long pasta",
  "long pepper",
  "long sweet pepper",
  "longan",
  "loquat",
  "lotus root",
  "lotus seed",
  "low carb bread",
  "low carb tortilla",
  "low fat buttermilk",
  "low fat cheese",
  "low fat chocolate milk",
  "low fat cottage cheese",
  "low fat graham crackers",
  "low fat greek yogurt",
  "low fat half and half",
  "low fat plain yogurt",
  "low fat ricotta cheese",
  "low fat shredded cheddar",
  "low fat shredded mexican cheese blend",
  "low fat shredded mozzarella",
  "low fat sweetened condensed milk",
  "low fat vanilla greek yogurt",
  "low fat vanilla yogurt",
  "low fat yogurt",
  "low moisture part skim mozzarella cheese",
  "low sodium baking powder",
  "low sodium beef broth",
  "low sodium broth",
  "low sodium chicken broth",
  "low sodium chicken stock",
  "low sodium vegetable broth",
  "low sugar ketchup",
  "lower sodium shoyu",
  "lower sodium soy sauce",
  "lucky charms cereal",
  "lucuma powder",
  "lump crabmeat",
  "lychee",
  "m&ms",
  "maca",
  "macadamia nuts",
  "macaroni",
  "macaroni and cheese",
  "mache",
  "mackerel",
  "mackerel fillets",
  "madeira",
  "mahi mahi",
  "mahi mahi fillets",
  "malt vinegar",
  "malted barley flour",
  "malted milk balls",
  "malted milk powder",
  "manchego cheese",
  "mandarin orange sections",
  "mandarin oranges",
  "mango",
  "mango chutney",
  "mango extract",
  "mango nectar",
  "mango pulp",
  "mango puree",
  "mango sorbet",
  "mangold",
  "mangosteen",
  "manicotti",
  "manila clams",
  "manzanilla olives",
  "maple extract",
  "maple flavoring",
  "maple sugar",
  "maple syrup",
  "maraschino cherries",
  "maraschino cherry syrup",
  "maraschino liqueur",
  "margarine",
  "margarita mix",
  "marie biscuits",
  "marinara sauce",
  "marinated artichoke hearts",
  "marinated artichokes",
  "marinated mushrooms",
  "marjoram",
  "marmalade",
  "marmite",
  "marrow bones",
  "marsala",
  "marshmallow bunnies",
  "marshmallow chicks",
  "marshmallow cream",
  "marshmallow peeps",
  "marshmallows",
  "marzipan",
  "masa harina",
  "mascarpone",
  "mashed banana",
  "mashed papaya",
  "matcha",
  "matzo",
  "matzo meal",
  "maui onion",
  "mayonnaise",
  "mcintosh apple",
  "mct oil",
  "meat",
  "meatballs",
  "meatloaf mix",
  "medium grain rice",
  "medjool dates",
  "merlot",
  "mesclun",
  "mexican cheese",
  "mexican crema",
  "mexicorn",
  "meyer lemon",
  "meyer lemon juice",
  "mezcal",
  "mezzelune",
  "microwave popcorn",
  "midori melon liqueur",
  "mild cheddar cheese",
  "milk",
  "milk chocolate",
  "milk chocolate chips",
  "milk substitute",
  "milky way",
  "millet",
  "millet flour",
  "mincemeat",
  "mineral water",
  "mini bagel",
  "mini chocolate chips",
  "mini filo shells",
  "mini m&ms",
  "mini marshmallows",
  "mini peppers",
  "mini rice cakes",
  "mini semisweet chocolate chips",
  "miniature peanut butter cups",
  "mint",
  "mint chutney",
  "mint jelly",
  "minute tapioca",
  "miracle whip",
  "mirepoix",
  "mirin",
  "miso",
  "mitsuba",
  "mixed baby greens",
  "mixed berries",
  "mixed fresh fruit",
  "mixed fruit",
  "mixed greens",
  "mixed mushrooms",
  "mixed seafood",
  "mixed spice",
  "mixed vegetables",
  "mizuna",
  "modeling chocolate",
  "molasses",
  "monk fruit extract",
  "monkfish",
  "monkfish cheeks",
  "monkfish fillets",
  "monterey jack cheese",
  "montreal steak seasoning",
  "moong dal",
  "morel mushrooms",
  "moringa leaves",
  "moringa powder",
  "mortadella",
  "moscato",
  "mostaccioli",
  "moth bean",
  "mounds bar",
  "mozzarella",
  "muenster",
  "muesli",
  "mulberries",
  "multigrain bread",
  "mung bean sprouts",
  "mung beans",
  "munster",
  "muscadine grapes",
  "muscovado sugar",
  "muscovy duck",
  "mushrooms",
  "muskmelon",
  "mussels",
  "mustard",
  "mustard greens",
  "mustard oil",
  "mustard powder",
  "mustard seeds",
  "naan",
  "nabulsi",
  "nacho cheese",
  "nacho cheese doritos",
  "napa cabbage",
  "napa cabbage leaves",
  "navel orange",
  "navy beans",
  "nectarine",
  "neem fruit",
  "neem leaves",
  "neufchatel",
  "new potato",
  "niger seed",
  "nilla wafers",
  "no calorie sweetener",
  "no calorie sweetener packet",
  "no salt added diced tomatoes",
  "nondairy butter",
  "nondairy creamer",
  "nonfat dry milk powder",
  "nonfat plain yogurt",
  "nonfat sour cream",
  "nonpareils",
  "nopales",
  "nori",
  "nougat",
  "nut butter",
  "nutmeg",
  "nutri grain cereal",
  "nutritional yeast",
  "nutritional yeast flakes",
  "nuts",
  "nutter butter cookies",
  "oat bran",
  "oat flakes",
  "oat flour",
  "oat milk",
  "oatmeal",
  "oats",
  "oaxaca cheese",
  "octopus",
  "off dry riesling",
  "oil cured black olives",
  "oil packed sun dried tomatoes",
  "oil packed tuna",
  "okara",
  "okra",
  "old bay seasoning",
  "olive oil",
  "olive oil spray",
  "olive tapenade",
  "olives",
  "onion",
  "onion dip",
  "onion powder",
  "onion roll",
  "onion salt",
  "orange",
  "orange bitters",
  "orange extract",
  "orange flavored gelatin",
  "orange flower water",
  "orange food color",
  "orange jello",
  "orange juice",
  "orange juice concentrate",
  "orange liqueur",
  "orange marmalade",
  "orange peel",
  "orange pepper",
  "orange roughy",
  "orange slices",
  "orange tomato",
  "orange zest",
  "orecchiette",
  "oregano",
  "oreo cookies",
  "orgeat syrup",
  "orzo",
  "osso buco",
  "ouzo",
  "ovaltine",
  "oven ready lasagne noodles",
  "oxtail",
  "oyster crackers",
  "oyster mushrooms",
  "oyster sauce",
  "oysters",
  "palm oil",
  "palm sugar",
  "palmyra",
  "pancake mix",
  "pancetta",
  "paneer",
  "panela",
  "pangasius",
  "panko",
  "papaya",
  "pappardelle",
  "paprika",
  "paratha",
  "parmesan",
  "parmigiano reggiano",
  "parsley",
  "parsnip",
  "part skim mozzarella cheese",
  "partially defatted soy flour",
  "partridge",
  "pasilla pepper",
  "passata",
  "passion fruit",
  "passion fruit juice",
  "pasta",
  "pasta dough",
  "pasta ribbons",
  "pasta salad mix",
  "pasta sauce",
  "pasta shells",
  "pastina",
  "pastrami",
  "pastry cream",
  "pastry dough",
  "pastry flour",
  "pattypan squash",
  "pawpaw",
  "pea protein powder",
  "pea shoots",
  "peach",
  "peach nectar",
  "peach preserves",
  "peach schnapps",
  "peach sorbet",
  "peanut butter",
  "peanut butter candy",
  "peanut butter chips",
  "peanut butter cookie mix",
  "peanut butter cups",
  "peanut flour",
  "peanut oil",
  "peanut sauce",
  "peanuts",
  "pear",
  "pear juice",
  "pear liqueur",
  "pear nectar",
  "pearl barley",
  "pearl millet",
  "pearl onion",
  "pearl sugar",
  "peas",
  "peas and carrots",
  "pecan pieces",
  "pecans",
  "pecorino",
  "pecorino romano",
  "pectin",
  "penne",
  "peperoncini",
  "pepper",
  "pepper and onion mix",
  "peppercorns",
  "pepperjack cheese",
  "peppermint candy",
  "peppermint crunch",
  "peppermint extract",
  "peppermint patties",
  "pepperoni",
  "pepperoni slices",
  "peppers",
  "pepsi",
  "perch",
  "pernod",
  "persian cucumber",
  "persimmon",
  "pesto",
  "petite peas",
  "petite tomatoes",
  "pheasant",
  "physalis",
  "picante sauce",
  "pickle juice",
  "pickle relish",
  "pickled beets",
  "pickled daikon",
  "pickled ginger",
  "pickled green beans",
  "pickled jalapenos",
  "pickled mustard greens",
  "pickles",
  "pickling spices",
  "pico de gallo",
  "pico piquin seasoning",
  "pie crust",
  "pie dough rounds",
  "pigeon",
  "pigeon breasts",
  "pigeon peas",
  "pike",
  "pils",
  "pimento cheese",
  "pimento stuffed green olives",
  "pimenton de la vera",
  "pimiento",
  "pimms",
  "pine nuts",
  "pineapple",
  "pineapple chunks",
  "pineapple in juice",
  "pineapple jam",
  "pineapple juice",
  "pineapple preserves",
  "pineapple rings",
  "pineapple tidbits",
  "pineapple with juice",
  "pink banana squash",
  "pink himalayan salt",
  "pink lady apple",
  "pinot grigio",
  "pinot noir",
  "pinto beans",
  "piquillo pepper",
  "pisco",
  "pistachio nuts",
  "pistachio oil",
  "pita",
  "pita chips",
  "pizza dough",
  "pizza dough mix",
  "pizza sauce",
  "pizza seasoning",
  "plaice",
  "plain doritos",
  "plain greek yogurt",
  "plain yogurt",
  "plantain",
  "plum",
  "plum preserves",
  "plum sauce",
  "plum tomato",
  "plum vinegar",
  "pluot",
  "poached egg",
  "poblano pepper",
  "pointed cabbage",
  "pointed gourd",
  "pointed pepper",
  "polenta",
  "pomegranate",
  "pomegranate juice",
  "pomegranate molasses",
  "pomegranate seeds",
  "pomegranate syrup",
  "pomelo",
  "pomfret",
  "ponzu sauce",
  "popcorn",
  "popcorn kernels",
  "poppy seeds",
  "poppyseed roll",
  "porgy",
  "pork",
  "pork and beans",
  "pork belly",
  "pork belly slices",
  "pork bone",
  "pork broth",
  "pork chops",
  "pork cutlets",
  "pork escalopes",
  "pork fat",
  "pork kidney",
  "pork knuckle",
  "pork liver",
  "pork loin",
  "pork loin chops",
  "pork rib roast",
  "pork ribs",
  "pork rinds",
  "pork roast",
  "pork sausage",
  "pork seasoning",
  "pork shank",
  "pork shoulder",
  "pork sirloin tip roast",
  "pork spare ribs",
  "pork steaks",
  "pork stock",
  "pork tenderloin",
  "port wine",
  "porter",
  "porterhouse steak",
  "portobello mushroom caps",
  "portobello mushrooms",
  "pot roast",
  "potato",
  "potato bread",
  "potato chips",
  "potato leaves",
  "potato roll",
  "potato salad",
  "potato starch",
  "potstickers",
  "poultry seasoning",
  "pound cake",
  "poussin",
  "powdered milk",
  "powdered peanut butter",
  "powdered peanut butter with chocolate",
  "powdered sugar",
  "powdered sugar substitute",
  "prepared pizza crust",
  "prepared polenta",
  "prepared whole wheat pizza crust",
  "preserved lemon",
  "preserves",
  "pretzel nuggets",
  "pretzel rods",
  "pretzel roll",
  "pretzel sticks",
  "pretzel twists",
  "pretzels",
  "prime rib",
  "prosciutto",
  "prosecco",
  "protein powder",
  "provolone",
  "provolone cheese slices",
  "prunes",
  "psyllium husk powder",
  "psyllium husks",
  "psyllium seed powder",
  "pudding mix",
  "puff pastry dough",
  "puff pastry sheets",
  "puff pastry shells",
  "puffed rice",
  "puffed rice cereal",
  "pulled pork",
  "pumpernickel",
  "pumpkin",
  "pumpkin blossoms",
  "pumpkin leaves",
  "pumpkin pie mix",
  "pumpkin pie spice",
  "pumpkin seed oil",
  "pumpkin seeds",
  "pumpkin spice pudding mix",
  "punt e mes",
  "purple plum",
  "purple potato",
  "quail",
  "quail eggs",
  "quark",
  "quesadilla cheese",
  "queso fresco",
  "quick cooking barley",
  "quick cooking grits",
  "quick cooking oats",
  "quick cooking tapioca",
  "quince",
  "quinoa",
  "quinoa flakes",
  "quinoa flour",
  "quinoa pasta",
  "quorn crumbles",
  "rabbit meat",
  "rack of lamb",
  "radicchio",
  "radish",
  "radish leaves",
  "radish sprouts",
  "rainbow trout",
  "rainbow trout fillets",
  "raisin bran",
  "raisin bread",
  "raisins",
  "raita",
  "rambutan",
  "ramen noodles",
  "ramps",
  "ramson",
  "ranch dressing",
  "ras el hanout",
  "raspberries",
  "raspberry extract",
  "raspberry flavored gelatin",
  "raspberry jam",
  "raspberry jelly",
  "raspberry liqueur",
  "raspberry preserves",
  "raspberry sauce",
  "raspberry vinaigrette",
  "raspberry vinegar",
  "ravioli",
  "raw cashews",
  "raw honey",
  "raw pumpkin seeds",
  "raw shrimp",
  "raw sugar",
  "ready to serve asian fried rice",
  "real bacon pieces",
  "red apple",
  "red bean paste",
  "red beet",
  "red belgian endive",
  "red cabbage",
  "red chili pepper",
  "red cinnamon candy",
  "red currant jelly",
  "red currants",
  "red curry paste",
  "red delicious apple",
  "red enchilada sauce",
  "red flesh navel orange",
  "red food color",
  "red glaze",
  "red grapefruit",
  "red grapes",
  "red jalapeno",
  "red kidney beans",
  "red kuri squash",
  "red leaf lettuce",
  "red leaf lettuce leaves",
  "red leicester",
  "red lentils",
  "red miso",
  "red mullet",
  "red onion",
  "red pearl onion",
  "red pepper",
  "red pepper flakes",
  "red pesto",
  "red plum",
  "red potato",
  "red skinned sweet potato",
  "red snapper",
  "red snapper fillets",
  "red tea bag",
  "red velvet cake mix",
  "red wine",
  "red wine vinegar",
  "redfish",
  "reduced fat and reduced sodium cream of celery soup",
  "reduced fat and reduced sodium cream of chicken soup",
  "reduced fat and reduced sodium cream of mushroom soup",
  "reduced fat chocolate milk",
  "reduced fat coleslaw dressing",
  "reduced fat cream cheese",
  "reduced fat cream of celery soup",
  "reduced fat cream of chicken soup",
  "reduced fat cream of mushroom soup",
  "reduced fat creme fraiche",
  "reduced fat crescent rolls",
  "reduced fat evaporated milk",
  "reduced fat feta cheese",
  "reduced fat mozzarella",
  "reduced fat parmesan cheese",
  "reduced fat peanut butter",
  "reduced fat string cheese",
  "reduced fat swiss cheese",
  "reduced sodium cream of chicken soup",
  "reduced sodium cream of mushroom soup",
  "reduced sodium tomato soup",
  "reeses pieces",
  "refried beans",
  "refrigerated cheese tortellini",
  "refrigerated crescent rolls",
  "refrigerated dough sheet",
  "refrigerated pie crust",
  "refrigerated pie dough",
  "refrigerated spinach tortellini",
  "refrigerated tortellini",
  "reindeer",
  "rhubarb",
  "rib tips",
  "ribbon fish",
  "ribeye steak",
  "ribs",
  "rice",
  "rice bran",
  "rice bran oil",
  "rice cakes",
  "rice chex",
  "rice flour",
  "rice krispies cereal",
  "rice milk",
  "rice noodles",
  "rice protein powder",
  "rice vermicelli",
  "rice vinegar",
  "rice wine",
  "ricotta cheese",
  "ricotta salata cheese",
  "ridge gourd",
  "riesling",
  "rigatoni",
  "ripe olives",
  "risotto rice",
  "roast beef",
  "roasted cashews",
  "roasted chicken",
  "roasted garlic",
  "roasted peanuts",
  "roasted pumpkin seeds",
  "roasted red peppers",
  "roasted salted sunflower seeds",
  "roasted unsalted pumpkin seeds",
  "roasting chicken",
  "rock salt",
  "rock shrimp",
  "rockfish",
  "rolled oats",
  "roma tomato",
  "romaine",
  "romaine hearts",
  "romanesco",
  "romano cheese",
  "rooibos",
  "root beer",
  "root vegetable",
  "roquefort cheese",
  "rose apple",
  "rose water",
  "rosehips",
  "roselle fruit",
  "rosemary",
  "rotini",
  "rotisserie chicken",
  "round steak",
  "round tip steak",
  "royal porgy",
  "rubbed sage",
  "rum",
  "rum extract",
  "rump roast",
  "runner beans",
  "runny honey",
  "russet potato",
  "rutabaga",
  "rye beer",
  "rye berries",
  "rye bread",
  "rye flour",
  "rye meal",
  "sablefish",
  "safflower oil",
  "safflower seeds",
  "saffron",
  "sage",
  "sago",
  "sake",
  "salad dressing",
  "salad oil",
  "salami",
  "salmon",
  "salmon caviar",
  "salmon fillets",
  "salmon roe",
  "salmon steak",
  "salsa",
  "salsa verde",
  "salt",
  "salt and pepper",
  "salt cod",
  "salt packed anchovies",
  "salt pork",
  "salted butter",
  "salted peanuts",
  "salted pork fat",
  "salted roasted cashews",
  "saltine crackers",
  "sambuca",
  "samphire",
  "sandwich bun",
  "sandwich cookies",
  "sandwich thin",
  "sapote",
  "sardines",
  "sardines in tomato sauce",
  "saucisses",
  "sauerkraut",
  "sausage",
  "sausage links",
  "sausage patties",
  "sauvignon blanc",
  "savoy cabbage",
  "savoy cabbage leaves",
  "sazon completa",
  "scallops",
  "schisandra berries",
  "schmaltz",
  "scoops tortilla chips",
  "scotch bonnet chili",
  "scotch whiskey",
  "scrapple",
  "sea bream",
  "sea cucumber",
  "sea salt",
  "sea vegetable",
  "seabass",
  "seabass fillets",
  "seafood seasoning",
  "seafood stock",
  "seasoned breadcrumbs",
  "seasoned flour",
  "seasoned rice vinegar",
  "seasoned salt",
  "seasoned soybean paste",
  "seasoning",
  "seasoning mix",
  "seaweed",
  "seedless cucumber",
  "seedless grapes",
  "seedless green grapes",
  "seedless red grapes",
  "seedless watermelon",
  "seeds",
  "seitan",
  "seitan cutlets",
  "seitan steaks",
  "self rising flour",
  "semisweet chocolate",
  "semisweet chocolate chips",
  "semolina",
  "semolina flour",
  "serrano pepper",
  "sesame oil",
  "sesame seed burger bun",
  "sesame seeds",
  "shallot",
  "shaoxing wine",
  "shark",
  "sharp cheddar cheese",
  "sheep cheese",
  "sheet gelatin",
  "shell topping",
  "shelled edamame",
  "sherbet",
  "sherry",
  "sherry vinegar",
  "shichimi togarashi",
  "shiitake mushrooms",
  "shirataki pasta",
  "shirataki rice",
  "shiraz",
  "shiso leaves",
  "short grain brown rice",
  "short grain rice",
  "short pasta",
  "shortbread cookies",
  "shortcrust pastry",
  "shortening",
  "shoulder joint of pork",
  "shoyu",
  "shredded cheddar cheese",
  "shredded cheese",
  "shredded chicken",
  "shredded mexican cheese blend",
  "shredded mozzarella",
  "shredded wheat cereal",
  "shrimp",
  "shrimp stock",
  "shucked oysters",
  "silken tofu",
  "silver tequila",
  "simple syrup",
  "single cream",
  "sirloin steak",
  "sirloin tip steak",
  "skate",
  "skate wings",
  "skim milk mozzarella",
  "skim milk quark",
  "skinless chicken drumsticks",
  "skinless chicken leg",
  "skinless chicken pieces",
  "skinless rotisserie chicken",
  "skirt steak",
  "slab bacon",
  "sliced almonds",
  "sliced chicken breast",
  "sliced roast beef",
  "sliced swiss cheese",
  "sliced turkey",
  "slider buns",
  "slivered almonds",
  "smoked haddock",
  "smoked ham",
  "smoked ham hock",
  "smoked paprika",
  "smoked salmon",
  "smoked sausage",
  "smoked trout",
  "snake gourd",
  "snapper",
  "snapper fillets",
  "snickers bar",
  "snow peas",
  "soba noodles",
  "sobrasada",
  "soft cheese",
  "soft pretzels",
  "sola sweetener",
  "sole",
  "solid white tuna packed in water",
  "soppressata",
  "sorbet",
  "sorghum",
  "sorghum flour",
  "sorrel",
  "sour cream",
  "sourdough bread",
  "sourdough starter",
  "soured milk",
  "southern comfort",
  "soy butter",
  "soy buttery spread",
  "soy cheese",
  "soy creamer",
  "soy flour",
  "soy lecithin granules",
  "soy nuts",
  "soy protein powder",
  "soy pudding",
  "soy sauce",
  "soy yogurt",
  "soybean oil",
  "soybeans",
  "soymilk",
  "spaghetti",
  "spaghetti sauce mix",
  "spaghetti squash",
  "spaghettini",
  "spam",
  "spanish chorizo",
  "spanish rice",
  "spare ribs",
  "sparkling water",
  "sparkling wine",
  "speck",
  "spelt",
  "spelt flour",
  "spice cake mix",
  "spice drops",
  "spice paste",
  "spiced rum",
  "spices",
  "spicy brown mustard",
  "spinach",
  "spinach fettuccine",
  "spinach tortellini",
  "spinach wrap",
  "spiny gourd",
  "spirulina",
  "splenda",
  "splenda brown sugar blend",
  "split peas",
  "split pigeon peas",
  "sponge cake",
  "sprats",
  "spring mix",
  "spring onions",
  "spring roll wrappers",
  "sprinkles",
  "sprouted grain bread",
  "sprouts",
  "squash",
  "squash blossoms",
  "squid",
  "squid ink pasta",
  "squid tubes",
  "sriracha",
  "star anise",
  "star apple",
  "starburst candies",
  "starch",
  "starchy potato",
  "starfruit",
  "steak",
  "steak sauce",
  "steak seasoning",
  "steel cut oats",
  "stevia",
  "stewed tomatoes",
  "stick margarine",
  "sticky rice",
  "stilton",
  "stinging nettle",
  "stock",
  "stock powder",
  "stone ground mustard",
  "stout",
  "straw mushrooms",
  "strawberries",
  "strawberry cake mix",
  "strawberry flavored gelatin",
  "strawberry ice cream",
  "strawberry jam",
  "strawberry jello",
  "strawberry jelly",
  "strawberry pie filling",
  "strawberry preserves",
  "strawberry puree",
  "strawberry sauce",
  "strawberry yogurt",
  "string cheese",
  "strip steak",
  "striped bass",
  "strong coffee",
  "stuffing",
  "stuffing mix",
  "sub bun",
  "sucanat",
  "sucralose",
  "suet",
  "sugar",
  "sugar alcohol",
  "sugar apple",
  "sugar cookie dough",
  "sugar cookie mix",
  "sugar cubes",
  "sugar free apricot jam",
  "sugar free apricot preserves",
  "sugar free blackberry jam",
  "sugar free blueberry jam",
  "sugar free blueberry jelly",
  "sugar free caramel sauce",
  "sugar free cheesecake pudding mix",
  "sugar free cherry jam",
  "sugar free cherry preserves",
  "sugar free chocolate chips",
  "sugar free chocolate pudding mix",
  "sugar free chocolate syrup",
  "sugar free grape jam",
  "sugar free grape jelly",
  "sugar free jam",
  "sugar free jelly",
  "sugar free marshmallows",
  "sugar free mini marshmallows",
  "sugar free pancake syrup",
  "sugar free preserves",
  "sugar free raspberry gelatin",
  "sugar free raspberry jam",
  "sugar free raspberry jelly",
  "sugar free raspberry preserves",
  "sugar free strawberry jam",
  "sugar free strawberry jelly",
  "sugar free strawberry preserves",
  "sugar free syrup",
  "sugar free vanilla pudding mix",
  "sugar free white chocolate pudding mix",
  "sugar in the raw",
  "sugar pumpkin",
  "sugar snap peas",
  "sugar substitute",
  "sukrin",
  "sumac",
  "summer savory",
  "summer squash",
  "sun dried tomatoes",
  "sundried tomato paste",
  "sundried tomato pesto",
  "sundried tomato wrap",
  "sunflower kernels",
  "sunflower oil",
  "sunflower seed butter",
  "sunflower seeds",
  "sunflower shoots",
  "superfine sugar",
  "sushi rice",
  "suze",
  "sweet butter",
  "sweet cherries",
  "sweet chili sauce",
  "sweet corn",
  "sweet corn on the cob",
  "sweet dumpling squash",
  "sweet gherkins",
  "sweet italian sausage",
  "sweet onion",
  "sweet paprika",
  "sweet pepper",
  "sweet pickle relish",
  "sweet pickles",
  "sweet potato",
  "sweet potato leaves",
  "sweet potato puree",
  "sweet potato vermicelli",
  "sweet rice flour",
  "sweet yellow onion",
  "sweetened coconut",
  "sweetened coconut flakes",
  "sweetened condensed milk",
  "sweetened condensed skim milk",
  "sweetened shredded coconut",
  "sweetened whipped cream",
  "swerve",
  "swerve confectioners",
  "swiss chard",
  "swiss cheese",
  "sword beans",
  "swordfish",
  "swordfish steaks",
  "t bone steak",
  "tabasco sauce",
  "table salt",
  "table syrup",
  "taco salad shells",
  "taco seasoning mix",
  "taco shells",
  "tagatose",
  "tagliatelle",
  "tahini",
  "tahitian vanilla bean",
  "taleggio cheese",
  "tamari",
  "tamarillo",
  "tamarind",
  "tamarind juice",
  "tamarind leaves",
  "tamarind paste",
  "tamarind pulp",
  "tangelo",
  "tangelo juice",
  "tangerine",
  "tangerine juice",
  "tapioca",
  "tapioca starch",
  "tapioca syrup",
  "taro leaves",
  "taro root",
  "tarragon",
  "tarragon vinegar",
  "tart apple",
  "tart cherries",
  "tart shells",
  "tartar sauce",
  "tartlet shells",
  "tater tots",
  "tea",
  "tea bag",
  "teff",
  "teff flour",
  "tempeh",
  "tempura batter mix",
  "tenderloin steak",
  "tengra",
  "tennessee honey",
  "tequila",
  "teriyaki sauce",
  "texas toast",
  "textured vegetable protein",
  "thai basil",
  "thai chili",
  "thai fish sauce",
  "thai red curry paste",
  "thick cut bacon",
  "thin baguette",
  "thousand island dressing",
  "thyme",
  "tia maria",
  "tiger nuts",
  "tiger shrimp",
  "tilapia",
  "tilapia fillets",
  "tinda",
  "toast",
  "toffee",
  "toffee bar candy",
  "toffee pieces",
  "tofu",
  "tomatillos",
  "tomato",
  "tomato and basil sauce",
  "tomato concentrate",
  "tomato juice",
  "tomato paste",
  "tomato pesto",
  "tomato puree",
  "tomato sauce",
  "tomato slices",
  "tomato soup",
  "tomatoes in juice",
  "tonic water",
  "tonka beans",
  "top blade steak",
  "top sirloin steak",
  "tortellini",
  "tortilla",
  "tortilla chips",
  "tortilla strips",
  "tostada shell",
  "tostadas",
  "tri color tortilla chipps",
  "tri tip roast",
  "tri tip steak",
  "tricolor pasta",
  "trimmed watercress",
  "triple sec",
  "triticale",
  "trout fillets",
  "truffle mushrooms",
  "truffle oil",
  "tubetti",
  "tubettini",
  "tuna",
  "tuna in olive oil",
  "tuna packed in water",
  "turbinado sugar",
  "turbot",
  "turkey bacon",
  "turkey berries",
  "turkey bratwurst",
  "turkey breast",
  "turkey breast cutlets",
  "turkey broth",
  "turkey burgers",
  "turkey drumsticks",
  "turkey fat",
  "turkey giblets",
  "turkey gizzards",
  "turkey gravy",
  "turkey hearts",
  "turkey kielbasa",
  "turkey leg",
  "turkey liver",
  "turkey meat",
  "turkey meatballs",
  "turkey necks",
  "turkey pastrami",
  "turkey pepperoni",
  "turkey sausage",
  "turkey stock",
  "turkey tenderloin",
  "turkey thigh",
  "turkey wings",
  "turkish bay leaves",
  "turmeric",
  "turmeric paste",
  "turnip",
  "turnip greens",
  "twix",
  "tzatziki",
  "udon noodles",
  "unbaked pie crust",
  "unbleached all purpose flour",
  "unbleached flour",
  "unsalted butter",
  "unsalted peanut butter",
  "unsalted peanuts",
  "unsalted pistachios",
  "unsalted sweet butter",
  "unseasoned rice vinegar",
  "unsulfured molasses",
  "unsweetened baking chocolate",
  "unsweetened cocoa powder",
  "unsweetened coconut",
  "unsweetened coconut flakes",
  "unsweetened coconut milk",
  "unsweetened dutch processed cocoa powder",
  "unsweetened shredded coconut",
  "unsweetened soymilk",
  "urad dal",
  "vanilla",
  "vanilla bean",
  "vanilla cake mix",
  "vanilla extract",
  "vanilla frosting",
  "vanilla frozen yogurt",
  "vanilla ice cream",
  "vanilla paste",
  "vanilla powder",
  "vanilla protein powder",
  "vanilla sandwich cookies",
  "vanilla sugar",
  "vanilla wafer cookies",
  "vanilla yogurt",
  "veal",
  "veal bone",
  "veal chops",
  "veal cutlet",
  "veal liver",
  "veal loin chops",
  "veal shank",
  "veal stock",
  "vegan buttery spread",
  "vegan buttery stick",
  "vegan cheddar cheese",
  "vegan cheese",
  "vegan cream cheese",
  "vegan mayonnaise",
  "vegan mozzarella",
  "vegan protein powder",
  "vegan sour cream",
  "vegeta",
  "vegetable",
  "vegetable bouillon cube",
  "vegetable broth",
  "vegetable juice",
  "vegetable oil",
  "vegetable oil cooking spray",
  "vegetable shortening",
  "vegetable stock",
  "vegetable tortellini",
  "vegetarian baked beans",
  "vegetarian chicken deli slices",
  "vegetarian parmesan",
  "veggie bacon",
  "veggie burger",
  "veggie crumbles",
  "veggie deli slices",
  "veggie dogs",
  "veggie meatballs",
  "veggie nuggets",
  "veggie sausage",
  "veggie sausage patties",
  "velveeta cheese",
  "venison",
  "venison chops",
  "venison loin",
  "venison ribs",
  "venison shoulder",
  "venison steak",
  "verjus",
  "vermouth",
  "vidalia onion",
  "vienna sausage",
  "vinaigrette",
  "vine ripened tomatoes",
  "vinegar",
  "virgin olive oil",
  "vital wheat gluten",
  "vodka",
  "waffle cone",
  "wakame",
  "walla walla",
  "walnut halves",
  "walnut oil",
  "walnut pieces",
  "walnuts",
  "wasabi",
  "wasabi paste",
  "wasabi peas",
  "wasabi powder",
  "water",
  "water chestnuts",
  "water spinach",
  "watercress",
  "watermelon",
  "watermelon radish",
  "wax beans",
  "wax chilies",
  "waxy potato",
  "weisswurst",
  "wensleydale",
  "wheat beer",
  "wheat bran",
  "wheat chex cereal",
  "wheat flakes",
  "wheat flatbreads",
  "wheat flour",
  "wheat germ",
  "wheat thins",
  "wheatberries",
  "whey protein powder",
  "whipped butter",
  "whipped cream",
  "whipped cream stabilizer",
  "whipped topping",
  "whipping cream",
  "whiskey",
  "white asparagus",
  "white balsamic vinegar",
  "white beans",
  "white bread",
  "white button mushrooms",
  "white cake mix",
  "white cheddar cheese",
  "white cheese dip",
  "white chocolate",
  "white chocolate chips",
  "white corn",
  "white corn tortilla",
  "white cornmeal",
  "white fish fillets",
  "white grape juice",
  "white grapefruit",
  "white kidney beans",
  "white miso",
  "white onion",
  "white pepper",
  "white peppercorns",
  "white potato",
  "white rice",
  "white sandwich bread",
  "white shoepeg corn",
  "white sweet potato",
  "white whole wheat flour",
  "white wine",
  "white wine vinegar",
  "white zinfandel",
  "whitebait",
  "whitefish",
  "whitefish fillets",
  "whiting",
  "whiting fillets",
  "whole chicken",
  "whole clove",
  "whole coconut",
  "whole coriander seeds",
  "whole cranberry sauce",
  "whole duck",
  "whole garlic cloves",
  "whole goose",
  "whole grain dijon mustard",
  "whole grain mustard",
  "whole grain spelt flour",
  "whole grain tortilla",
  "whole grain wrap",
  "whole kernel corn",
  "whole milk",
  "whole rabbit",
  "whole tomato",
  "whole turkey",
  "whole wheat angel hair pasta",
  "whole wheat bread",
  "whole wheat breadcrumbs",
  "whole wheat chex",
  "whole wheat couscous",
  "whole wheat crackers",
  "whole wheat elbow macaroni",
  "whole wheat english muffins",
  "whole wheat farfalle",
  "whole wheat flour",
  "whole wheat fusilli",
  "whole wheat hamburger bun",
  "whole wheat hot dog bun",
  "whole wheat lasagne noodles",
  "whole wheat pasta",
  "whole wheat pasta shells",
  "whole wheat pastry flour",
  "whole wheat penne",
  "whole wheat pita",
  "whole wheat pizza dough",
  "whole wheat pretzels",
  "whole wheat ravioli",
  "whole wheat rolls",
  "whole wheat spaghetti",
  "whole wheat tortilla",
  "whole wheat wrap",
  "wide egg noodles",
  "wild blueberries",
  "wild boar chops",
  "wild boar shank",
  "wild boar shoulder",
  "wild boar stew meat",
  "wild boar tenderloins",
  "wild fish",
  "wild leek",
  "wild rice",
  "wine",
  "wine vinegar",
  "winged bean",
  "winter squash",
  "wondra flour",
  "wonton wrappers",
  "worcestershire sauce",
  "wrap",
  "writing icing",
  "xanthan gum",
  "xylitol",
  "yacon syrup",
  "yam",
  "yardlong beans",
  "yeast",
  "yeast dinner rolls",
  "yeast water",
  "yellow cake mix",
  "yellow cherry tomato",
  "yellow cornmeal",
  "yellow curry paste",
  "yellow food color",
  "yellow miso",
  "yellow mustard",
  "yellow mustard seeds",
  "yellow onion",
  "yellow passion fruit",
  "yellow pepper",
  "yellow plantain",
  "yellow spice drops",
  "yellow split peas",
  "yellow squash",
  "yellow tomato",
  "yellow wax beans",
  "yellowfin tuna",
  "yellowtail snapper",
  "yogurt",
  "yukon gold potato",
  "yuzu",
  "yuzu juice",
  "zaatar",
  "zinfandel",
  "ziti",
  "zucchini",
  "zucchini noodles"
];

class TrieNode {
  constructor() {
    this.children = {};
    this.matches = []; // top-10 ingredient names reachable from this prefix
  }
}

class Trie {
  constructor() {
    this.root = new TrieNode();
  }

  insert(name) {
    let node = this.root;
    for (const char of name) {
      if (!node.children[char]) node.children[char] = new TrieNode();
      node = node.children[char];
      if (node.matches.length < 10) node.matches.push(name);
    }
  }

  search(query, limit = 10) {
    if (!query) return [];
    let node = this.root;
    for (const char of query.toLowerCase()) {
      if (!node.children[char]) return [];
      node = node.children[char];
    }
    return node.matches.slice(0, limit);
  }
}

// Build trie once at module load — synchronous, no network
const trie = new Trie();
for (const name of INGREDIENTS) trie.insert(name.toLowerCase());

/**
 * Drop-in replacement for ingredientAutocomplete().
 * Returns up to 10 matching ingredient name strings.
 * @param {string} query
 * @returns {string[]}
 */
export function ingredientAutocomplete(query) {
  return trie.search(query.trim());
}
